//! Directory walker for Scout.
//!
//! # Filtering pipeline (in order)
//!
//! 1. **`.gitignore` / `.ignore` / `.scoutignore`** — via the `ignore` crate,
//!    same engine as ripgrep. If the project already told git to ignore
//!    something, we skip it. This handles node_modules, dist, .next, venv,
//!    and anything else project-specific — automatically, without a static list.
//!
//! 2. **Hard-coded directory blocklist** — safety net for repos without a
//!    .gitignore (or incomplete ones). Also covers our own `.codesearch/` dir.
//!
//! 3. **File-name pattern blocklist** — catches generated files that have valid
//!    source extensions: `.d.ts`, `.min.js`, `.pb.go`, etc.
//!
//! 4. **Supported extension check** — only file types we can parse.
//!
//! 5. **Size limits** — skip files > 1 MB or with > 10 000 lines.
//!
//! 6. **Content heuristics** — generated-file markers in the first 512 bytes,
//!    minified files (any line > 500 chars), binary files (null bytes).

use std::path::{Path, PathBuf};

use ignore::WalkBuilder;

use crate::types::Language;

// ─── Hard-coded directory blocklist ──────────────────────────────────────────
//
// These are the directories we *always* skip, even without a .gitignore.
// Keep this list short — .gitignore should do the heavy lifting.

const BLOCKED_DIRS: &[&str] = &[
    // Our own index
    ".codesearch",
    ".scout",
    // VCS internals (git itself is handled by the ignore crate, but be explicit)
    ".git",
    ".svn",
    ".hg",
    // IDE state — never code
    ".idea",
    ".vscode",
    // Python bytecode — always regenerated, never source
    "__pycache__",
    // Rust compilation output
    "target",
    // macOS noise
    ".DS_Store",
];

/// Directory name prefixes that are always excluded, e.g. `dist-esm`, `build-cjs`.
const BLOCKED_DIR_PREFIXES: &[&str] = &["dist-", "build-", ".cache-", "bazel-"];

// ─── File-name pattern blocklist ─────────────────────────────────────────────
//
// Files whose names end with these suffixes are skipped even if they have a
// supported extension. All comparisons are done on the lowercased filename.

const BLOCKED_FILE_SUFFIXES: &[&str] = &[
    // TypeScript declarations — types only, no implementation
    ".d.ts",
    ".d.mts",
    ".d.cts",
    // Minified / bundled
    ".min.js",
    ".min.mjs",
    ".min.css",
    ".bundle.js",
    ".chunk.js",
    // Protobuf / gRPC generated stubs
    ".pb.go",
    ".pb.js",
    ".pb.ts",
    "_pb.js",
    "_pb.d.ts",
    // Common codegen suffixes
    ".generated.ts",
    ".generated.go",
    ".generated.js",
    ".gen.go",
    ".gen.ts",
];

// ─── Generated-file header markers ───────────────────────────────────────────
//
// If any of these strings appear in the first 512 bytes, we skip the file.
// These cover Go toolchain, protobuf, OpenAPI, Java annotation processors, etc.

const GENERATED_MARKERS: &[&str] = &[
    "// Code generated",
    "// DO NOT EDIT",
    "// This file is auto-generated",
    "// This file was automatically generated",
    "// AUTO-GENERATED FILE",
    "// AUTOGENERATED FILE",
    "// Generated by",
    "/* Generated by",
    "/* eslint-disable */",
    "# This file is auto-generated",
    "# DO NOT EDIT",
    "# Generated by",
    "# GENERATED FILE",
    "// Generated by the protocol buffer compiler",
    "@javax.annotation.Generated",
    "@jakarta.annotation.Generated",
    "* Do not edit the class manually",
    "* @auto-generated",
];

// ─── Size limits ──────────────────────────────────────────────────────────────

const MAX_FILE_BYTES: u64 = 1_000_000; // 1 MB
const MAX_FILE_LINES: usize = 10_000;

/// Minification heuristic: any single line longer than this is a red flag.
const MAX_LINE_LEN: usize = 500;

// ─── Public API ───────────────────────────────────────────────────────────────

/// Walk `root`, yielding paths to source files that should be indexed.
///
/// Respects `.gitignore`, `.ignore`, global gitignore, `.git/info/exclude`,
/// and a project-specific `.scoutignore` file.
pub fn walk_source_files(root: &Path) -> Vec<PathBuf> {
    WalkBuilder::new(root)
        // Respect all ignore files — this is the core of the filtering.
        .git_ignore(true)
        .git_global(true)
        .git_exclude(true)
        .ignore(true)
        // Allow projects to add Scout-specific exclusions.
        .add_custom_ignore_filename(".scoutignore")
        // Skip hidden files/dirs that aren't already caught by .gitignore.
        // (hidden dirs like .git, .venv are usually in .gitignore too,
        //  but this is a safe belt-and-suspenders measure)
        .hidden(true)
        // Don't follow symlinks — avoids infinite loops.
        .follow_links(false)
        .filter_entry(|e| {
            // Hard-coded dir blocklist on top of .gitignore.
            if e.file_type().map(|ft| ft.is_dir()).unwrap_or(false) {
                let name = e.file_name().to_str().unwrap_or("");
                if BLOCKED_DIRS.contains(&name) {
                    return false;
                }
                if BLOCKED_DIR_PREFIXES.iter().any(|p| name.starts_with(p)) {
                    return false;
                }
            }
            true
        })
        .build()
        .filter_map(|entry| entry.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_file()).unwrap_or(false))
        .filter(|e| !has_blocked_suffix(e.path()))
        .filter(|e| is_supported_extension(e.path()))
        .filter(|e| {
            e.metadata()
                .map(|m| m.len() > 0 && m.len() <= MAX_FILE_BYTES)
                .unwrap_or(false)
        })
        .filter(|e| !has_bad_content(e.path()))
        .map(|e| e.into_path())
        .collect()
}

/// Returns true if the path has a supported source file extension.
pub fn is_supported_extension(path: &Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|ext| !matches!(Language::from_extension(ext), Language::Unknown))
        .unwrap_or(false)
}

/// Returns true if a file's content is within the indexable line limit.
pub fn within_line_limit(content: &str) -> bool {
    content.chars().filter(|&c| c == '\n').count() < MAX_FILE_LINES
}

/// Returns the set of hard-blocked directory names (for the native file watcher).
pub fn excluded_dirs() -> std::collections::HashSet<&'static str> {
    BLOCKED_DIRS.iter().copied().collect()
}

// ─── Internals ────────────────────────────────────────────────────────────────

fn has_blocked_suffix(path: &Path) -> bool {
    let name = match path.file_name().and_then(|n| n.to_str()) {
        Some(n) => n.to_lowercase(),
        None => return false,
    };
    BLOCKED_FILE_SUFFIXES.iter().any(|s| name.ends_with(s))
}

/// Read the first 512 bytes and check for:
///   - Generated-file markers
///   - Binary data (null bytes)
///   - Minified content (any line > MAX_LINE_LEN chars)
fn has_bad_content(path: &Path) -> bool {
    use std::io::Read;

    let mut buf = [0u8; 512];
    let n = match std::fs::File::open(path).and_then(|mut f| f.read(&mut buf)) {
        Ok(n) => n,
        Err(_) => return true, // can't read → skip
    };

    let bytes = &buf[..n];

    // Binary file: contains null bytes.
    if bytes.contains(&0u8) {
        return true;
    }

    let header = match std::str::from_utf8(bytes) {
        Ok(s) => s,
        Err(_) => return true, // not valid UTF-8 → skip
    };

    // Generated-file markers.
    if GENERATED_MARKERS.iter().any(|m| header.contains(m)) {
        return true;
    }

    // Minification heuristic: any line longer than MAX_LINE_LEN chars.
    if header.lines().any(|l| l.len() > MAX_LINE_LEN) {
        return true;
    }

    false
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn make_file(dir: &Path, rel: &str, content: &str) {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    fn paths(files: &[PathBuf]) -> Vec<String> {
        files
            .iter()
            .map(|p| p.to_string_lossy().to_string())
            .collect()
    }

    // ── gitignore integration ──────────────────────────────────────────────

    #[test]
    fn respects_gitignore() {
        let tmp = TempDir::new().unwrap();
        // Init a git repo so the ignore crate picks up .gitignore.
        std::process::Command::new("git")
            .args(["init", "-q"])
            .current_dir(tmp.path())
            .output()
            .ok();

        make_file(tmp.path(), ".gitignore", "node_modules/\ndist/\n*.min.js\n");
        make_file(tmp.path(), "src/app.ts", "export function main() {}");
        make_file(tmp.path(), "node_modules/react/index.js", "module.exports={}");
        make_file(tmp.path(), "dist/bundle.js", "!function(){}()");
        make_file(tmp.path(), "static/vendor.min.js", "!function(){}()");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);

        assert!(ps.iter().any(|p| p.contains("src/app.ts")));
        assert!(!ps.iter().any(|p| p.contains("node_modules")));
        assert!(!ps.iter().any(|p| p.contains("dist/")));
        assert!(!ps.iter().any(|p| p.contains("vendor.min.js")));
    }

    #[test]
    fn respects_scoutignore() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), ".scoutignore", "fixtures/\n*.snapshot.ts\n");
        make_file(tmp.path(), "src/service.ts", "export function run() {}");
        make_file(tmp.path(), "fixtures/data.ts", "export const x = 1;");
        make_file(tmp.path(), "src/auth.snapshot.ts", "export const snap = {};");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);

        assert!(ps.iter().any(|p| p.contains("src/service.ts")));
        assert!(!ps.iter().any(|p| p.contains("fixtures/")));
        assert!(!ps.iter().any(|p| p.contains(".snapshot.ts")));
    }

    // ── hard-coded blocklist ───────────────────────────────────────────────

    #[test]
    fn blocks_pycache_and_git() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "lib.py", "def foo(): pass");
        make_file(tmp.path(), "__pycache__/lib.cpython-311.pyc", "\x00\x00");
        make_file(tmp.path(), ".git/COMMIT_EDITMSG", "fix: bug");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(!ps.iter().any(|p| p.contains("__pycache__")));
        assert!(!ps.iter().any(|p| p.contains(".git")));
    }

    #[test]
    fn blocks_dist_prefix_dirs() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "src/lib.ts", "export const x = 1;");
        make_file(tmp.path(), "dist-esm/lib.js", "export const x = 1;");
        make_file(tmp.path(), "dist-cjs/lib.js", "module.exports = {};");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.contains("src/lib.ts")));
        assert!(!ps.iter().any(|p| p.contains("dist-")));
    }

    // ── file-name patterns ─────────────────────────────────────────────────

    #[test]
    fn blocks_declaration_files() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "src/auth.ts", "export function login() {}");
        make_file(tmp.path(), "src/types.d.ts", "export type User = { id: number };");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.contains("src/auth.ts")));
        assert!(!ps.iter().any(|p| p.ends_with("types.d.ts")));
    }

    #[test]
    fn blocks_protobuf_generated() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "api/service.go", "package api\nfunc New() {}");
        make_file(tmp.path(), "api/service.pb.go", "package api");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.contains("api/service.go")));
        assert!(!ps.iter().any(|p| p.ends_with("service.pb.go")));
    }

    // ── content heuristics ─────────────────────────────────────────────────

    #[test]
    fn blocks_generated_marker_in_header() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "src/real.go", "package main\nfunc Real() {}");
        make_file(
            tmp.path(),
            "src/mock.go",
            "// Code generated by mockgen. DO NOT EDIT.\npackage main",
        );

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.contains("src/real.go")));
        assert!(!ps.iter().any(|p| p.ends_with("mock.go")));
    }

    #[test]
    fn blocks_minified_by_line_length() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "src/app.js", "function hello() { return 42; }");
        // Simulate a minified file: one very long line.
        let minified = "x".repeat(600);
        make_file(tmp.path(), "src/vendor.js", &minified);

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.ends_with("app.js")));
        assert!(!ps.iter().any(|p| p.ends_with("vendor.js")));
    }

    #[test]
    fn blocks_binary_files() {
        let tmp = TempDir::new().unwrap();
        // A .go file with a null byte — treated as binary.
        make_file(tmp.path(), "src/corrupt.go", "package main\x00garbage");
        make_file(tmp.path(), "src/real.go", "package main\nfunc f() {}");

        let files = walk_source_files(tmp.path());
        let ps = paths(&files);
        assert!(ps.iter().any(|p| p.ends_with("real.go")));
        assert!(!ps.iter().any(|p| p.ends_with("corrupt.go")));
    }

    // ── extension filtering ────────────────────────────────────────────────

    #[test]
    fn only_indexes_source_extensions() {
        let tmp = TempDir::new().unwrap();
        make_file(tmp.path(), "a.py", "x = 1");
        make_file(tmp.path(), "b.rs", "fn f() {}");
        make_file(tmp.path(), "c.ts", "const x = 1");
        make_file(tmp.path(), "d.go", "package main");
        make_file(tmp.path(), "e.md", "# docs");
        make_file(tmp.path(), "f.txt", "hello");

        let files = walk_source_files(tmp.path());
        assert_eq!(files.len(), 4);
    }
}
